package com.moonsworth.lunar.client.framework.feature.itemcounter.mixin;

import com.moonsworth.lunar.bridge.Bridge;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Unmodifiable;

public class Itemcounter {
   private static final Map<String, String> field1 = new HashMap<>();
   private static final Map<String, List<Itemcounter.Data>> field2 = new HashMap<>();

   public static @Unmodifiable List<Itemcounter.Data> method1(String var0) {
      return !field2.containsKey(var0) ? List.of() : Collections.unmodifiableList(field2.get(var0));
   }

   @NotNull
   public static String method2(@NotNull String var0, int var1) {
      return field1.get(var0 + "." + var1);
   }

   static {
      field1.put("minecraft:stone.0", "minecraft:stone");
      field1.put("minecraft:stone.1", "minecraft:granite");
      field1.put("minecraft:stone.2", "minecraft:polished_granite");
      field1.put("minecraft:stone.3", "minecraft:diorite");
      field1.put("minecraft:stone.4", "minecraft:polished_diorite");
      field1.put("minecraft:stone.5", "minecraft:andesite");
      field1.put("minecraft:stone.6", "minecraft:polished_andesite");
      field1.put("minecraft:dirt.0", "minecraft:dirt");
      field1.put("minecraft:dirt.1", "minecraft:coarse_dirt");
      field1.put("minecraft:dirt.2", "minecraft:podzol");
      field1.put("minecraft:leaves.0", "minecraft:oak_leaves");
      field1.put("minecraft:leaves.1", "minecraft:spruce_leaves");
      field1.put("minecraft:leaves.2", "minecraft:birch_leaves");
      field1.put("minecraft:leaves.3", "minecraft:jungle_leaves");
      field1.put("minecraft:leaves2.0", "minecraft:acacia_leaves");
      field1.put("minecraft:leaves2.1", "minecraft:dark_oak_leaves");
      field1.put("minecraft:log.0", "minecraft:oak_log");
      field1.put("minecraft:log.1", "minecraft:spruce_log");
      field1.put("minecraft:log.2", "minecraft:birch_log");
      field1.put("minecraft:log.3", "minecraft:jungle_log");
      field1.put("minecraft:log2.0", "minecraft:acacia_log");
      field1.put("minecraft:log2.1", "minecraft:dark_oak_log");
      field1.put("minecraft:sapling.0", "minecraft:oak_sapling");
      field1.put("minecraft:sapling.1", "minecraft:spruce_sapling");
      field1.put("minecraft:sapling.2", "minecraft:birch_sapling");
      field1.put("minecraft:sapling.3", "minecraft:jungle_sapling");
      field1.put("minecraft:sapling.4", "minecraft:acacia_sapling");
      field1.put("minecraft:sapling.5", "minecraft:dark_oak_sapling");
      field1.put("minecraft:planks.0", "minecraft:oak_planks");
      field1.put("minecraft:planks.1", "minecraft:spruce_planks");
      field1.put("minecraft:planks.2", "minecraft:birch_planks");
      field1.put("minecraft:planks.3", "minecraft:jungle_planks");
      field1.put("minecraft:planks.4", "minecraft:acacia_planks");
      field1.put("minecraft:planks.5", "minecraft:dark_oak_planks");
      field1.put("minecraft:sand.0", "minecraft:sand");
      field1.put("minecraft:sand.1", "minecraft:red_sand");
      field1.put("minecraft:quartz_block.0", "minecraft:quartz_block");
      field1.put("minecraft:quartz_block.1", "minecraft:chiseled_quartz_block");
      field1.put("minecraft:quartz_block.2", "minecraft:quartz_pillar");
      field1.put("minecraft:anvil.0", "minecraft:anvil");
      field1.put("minecraft:anvil.1", "minecraft:chipped_anvil");
      field1.put("minecraft:anvil.2", "minecraft:damaged_anvil");
      field1.put("minecraft:wool.0", "minecraft:white_wool");
      field1.put("minecraft:wool.1", "minecraft:orange_wool");
      field1.put("minecraft:wool.2", "minecraft:magenta_wool");
      field1.put("minecraft:wool.3", "minecraft:light_blue_wool");
      field1.put("minecraft:wool.4", "minecraft:yellow_wool");
      field1.put("minecraft:wool.5", "minecraft:lime_wool");
      field1.put("minecraft:wool.6", "minecraft:pink_wool");
      field1.put("minecraft:wool.7", "minecraft:gray_wool");
      field1.put("minecraft:wool.8", "minecraft:light_gray_wool");
      field1.put("minecraft:wool.9", "minecraft:cyan_wool");
      field1.put("minecraft:wool.10", "minecraft:purple_wool");
      field1.put("minecraft:wool.11", "minecraft:blue_wool");
      field1.put("minecraft:wool.12", "minecraft:brown_wool");
      field1.put("minecraft:wool.13", "minecraft:green_wool");
      field1.put("minecraft:wool.14", "minecraft:red_wool");
      field1.put("minecraft:wool.15", "minecraft:black_wool");
      field1.put("minecraft:carpet.0", "minecraft:white_carpet");
      field1.put("minecraft:carpet.1", "minecraft:orange_carpet");
      field1.put("minecraft:carpet.2", "minecraft:magenta_carpet");
      field1.put("minecraft:carpet.3", "minecraft:light_blue_carpet");
      field1.put("minecraft:carpet.4", "minecraft:yellow_carpet");
      field1.put("minecraft:carpet.5", "minecraft:lime_carpet");
      field1.put("minecraft:carpet.6", "minecraft:pink_carpet");
      field1.put("minecraft:carpet.7", "minecraft:gray_carpet");
      field1.put("minecraft:carpet.8", "minecraft:light_gray_carpet");
      field1.put("minecraft:carpet.9", "minecraft:cyan_carpet");
      field1.put("minecraft:carpet.10", "minecraft:purple_carpet");
      field1.put("minecraft:carpet.11", "minecraft:blue_carpet");
      field1.put("minecraft:carpet.12", "minecraft:brown_carpet");
      field1.put("minecraft:carpet.13", "minecraft:green_carpet");
      field1.put("minecraft:carpet.14", "minecraft:red_carpet");
      field1.put("minecraft:carpet.15", "minecraft:black_carpet");
      field1.put("minecraft:hardened_clay.0", "minecraft:terracotta");
      field1.put("minecraft:stained_hardened_clay.0", "minecraft:white_terracotta");
      field1.put("minecraft:stained_hardened_clay.1", "minecraft:orange_terracotta");
      field1.put("minecraft:stained_hardened_clay.2", "minecraft:magenta_terracotta");
      field1.put("minecraft:stained_hardened_clay.3", "minecraft:light_blue_terracotta");
      field1.put("minecraft:stained_hardened_clay.4", "minecraft:yellow_terracotta");
      field1.put("minecraft:stained_hardened_clay.5", "minecraft:lime_terracotta");
      field1.put("minecraft:stained_hardened_clay.6", "minecraft:pink_terracotta");
      field1.put("minecraft:stained_hardened_clay.7", "minecraft:gray_terracotta");
      field1.put("minecraft:stained_hardened_clay.8", "minecraft:light_gray_terracotta");
      field1.put("minecraft:stained_hardened_clay.9", "minecraft:cyan_terracotta");
      field1.put("minecraft:stained_hardened_clay.10", "minecraft:purple_terracotta");
      field1.put("minecraft:stained_hardened_clay.11", "minecraft:blue_terracotta");
      field1.put("minecraft:stained_hardened_clay.12", "minecraft:brown_terracotta");
      field1.put("minecraft:stained_hardened_clay.13", "minecraft:green_terracotta");
      field1.put("minecraft:stained_hardened_clay.14", "minecraft:red_terracotta");
      field1.put("minecraft:stained_hardened_clay.15", "minecraft:black_terracotta");
      field1.put("minecraft:silver_glazed_terracotta.0", "minecraft:light_gray_glazed_terracotta");
      field1.put("minecraft:stained_glass.0", "minecraft:white_stained_glass");
      field1.put("minecraft:stained_glass.1", "minecraft:orange_stained_glass");
      field1.put("minecraft:stained_glass.2", "minecraft:magenta_stained_glass");
      field1.put("minecraft:stained_glass.3", "minecraft:light_blue_stained_glass");
      field1.put("minecraft:stained_glass.4", "minecraft:yellow_stained_glass");
      field1.put("minecraft:stained_glass.5", "minecraft:lime_stained_glass");
      field1.put("minecraft:stained_glass.6", "minecraft:pink_stained_glass");
      field1.put("minecraft:stained_glass.7", "minecraft:gray_stained_glass");
      field1.put("minecraft:stained_glass.8", "minecraft:light_gray_stained_glass");
      field1.put("minecraft:stained_glass.9", "minecraft:cyan_stained_glass");
      field1.put("minecraft:stained_glass.10", "minecraft:purple_stained_glass");
      field1.put("minecraft:stained_glass.11", "minecraft:blue_stained_glass");
      field1.put("minecraft:stained_glass.12", "minecraft:brown_stained_glass");
      field1.put("minecraft:stained_glass.13", "minecraft:green_stained_glass");
      field1.put("minecraft:stained_glass.14", "minecraft:red_stained_glass");
      field1.put("minecraft:stained_glass.15", "minecraft:black_stained_glass");
      field1.put("minecraft:stained_glass_pane.0", "minecraft:white_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.1", "minecraft:orange_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.2", "minecraft:magenta_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.3", "minecraft:light_blue_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.4", "minecraft:yellow_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.5", "minecraft:lime_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.6", "minecraft:pink_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.7", "minecraft:gray_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.8", "minecraft:light_gray_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.9", "minecraft:cyan_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.10", "minecraft:purple_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.11", "minecraft:blue_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.12", "minecraft:brown_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.13", "minecraft:green_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.14", "minecraft:red_stained_glass_pane");
      field1.put("minecraft:stained_glass_pane.15", "minecraft:black_stained_glass_pane");
      field1.put("minecraft:prismarine.0", "minecraft:prismarine");
      field1.put("minecraft:prismarine.1", "minecraft:prismarine_bricks");
      field1.put("minecraft:prismarine.2", "minecraft:dark_prismarine");
      field1.put("minecraft:concrete.0", "minecraft:white_concrete");
      field1.put("minecraft:concrete.1", "minecraft:orange_concrete");
      field1.put("minecraft:concrete.2", "minecraft:magenta_concrete");
      field1.put("minecraft:concrete.3", "minecraft:light_blue_concrete");
      field1.put("minecraft:concrete.4", "minecraft:yellow_concrete");
      field1.put("minecraft:concrete.5", "minecraft:lime_concrete");
      field1.put("minecraft:concrete.6", "minecraft:pink_concrete");
      field1.put("minecraft:concrete.7", "minecraft:gray_concrete");
      field1.put("minecraft:concrete.8", "minecraft:light_gray_concrete");
      field1.put("minecraft:concrete.9", "minecraft:cyan_concrete");
      field1.put("minecraft:concrete.10", "minecraft:purple_concrete");
      field1.put("minecraft:concrete.11", "minecraft:blue_concrete");
      field1.put("minecraft:concrete.12", "minecraft:brown_concrete");
      field1.put("minecraft:concrete.13", "minecraft:green_concrete");
      field1.put("minecraft:concrete.14", "minecraft:red_concrete");
      field1.put("minecraft:concrete.15", "minecraft:black_concrete");
      field1.put("minecraft:concrete_powder.0", "minecraft:white_concrete_powder");
      field1.put("minecraft:concrete_powder.1", "minecraft:orange_concrete_powder");
      field1.put("minecraft:concrete_powder.2", "minecraft:magenta_concrete_powder");
      field1.put("minecraft:concrete_powder.3", "minecraft:light_blue_concrete_powder");
      field1.put("minecraft:concrete_powder.4", "minecraft:yellow_concrete_powder");
      field1.put("minecraft:concrete_powder.5", "minecraft:lime_concrete_powder");
      field1.put("minecraft:concrete_powder.6", "minecraft:pink_concrete_powder");
      field1.put("minecraft:concrete_powder.7", "minecraft:gray_concrete_powder");
      field1.put("minecraft:concrete_powder.8", "minecraft:light_gray_concrete_powder");
      field1.put("minecraft:concrete_powder.9", "minecraft:cyan_concrete_powder");
      field1.put("minecraft:concrete_powder.10", "minecraft:purple_concrete_powder");
      field1.put("minecraft:concrete_powder.11", "minecraft:blue_concrete_powder");
      field1.put("minecraft:concrete_powder.12", "minecraft:brown_concrete_powder");
      field1.put("minecraft:concrete_powder.13", "minecraft:green_concrete_powder");
      field1.put("minecraft:concrete_powder.14", "minecraft:red_concrete_powder");
      field1.put("minecraft:concrete_powder.15", "minecraft:black_concrete_powder");
      field1.put("minecraft:cobblestone_wall.0", "minecraft:cobblestone_wall");
      field1.put("minecraft:cobblestone_wall.1", "minecraft:mossy_cobblestone_wall");
      field1.put("minecraft:sandstone.0", "minecraft:sandstone");
      field1.put("minecraft:sandstone.1", "minecraft:chiseled_sandstone");
      field1.put("minecraft:sandstone.2", "minecraft:cut_sandstone");
      field1.put("minecraft:red_sandstone.0", "minecraft:red_sandstone");
      field1.put("minecraft:red_sandstone.1", "minecraft:chiseled_red_sandstone");
      field1.put("minecraft:red_sandstone.2", "minecraft:cut_red_sandstone");
      field1.put("minecraft:stonebrick.0", "minecraft:stone_bricks");
      field1.put("minecraft:stonebrick.1", "minecraft:mossy_stone_bricks");
      field1.put("minecraft:stonebrick.2", "minecraft:cracked_stone_bricks");
      field1.put("minecraft:stonebrick.3", "minecraft:chiseled_stone_bricks");
      field1.put("minecraft:monster_egg.0", "minecraft:infested_stone");
      field1.put("minecraft:monster_egg.1", "minecraft:infested_cobblestone");
      field1.put("minecraft:monster_egg.2", "minecraft:infested_stone_bricks");
      field1.put("minecraft:monster_egg.3", "minecraft:infested_mossy_stone_bricks");
      field1.put("minecraft:monster_egg.4", "minecraft:infested_cracked_stone_bricks");
      field1.put("minecraft:monster_egg.5", "minecraft:infested_chiseled_stone_bricks");
      field1.put("minecraft:yellow_flower.0", "minecraft:dandelion");
      field1.put("minecraft:red_flower.0", "minecraft:poppy");
      field1.put("minecraft:red_flower.1", "minecraft:blue_orchid");
      field1.put("minecraft:red_flower.2", "minecraft:allium");
      field1.put("minecraft:red_flower.3", "minecraft:azure_bluet");
      field1.put("minecraft:red_flower.4", "minecraft:red_tulip");
      field1.put("minecraft:red_flower.5", "minecraft:orange_tulip");
      field1.put("minecraft:red_flower.6", "minecraft:white_tulip");
      field1.put("minecraft:red_flower.7", "minecraft:pink_tulip");
      field1.put("minecraft:red_flower.8", "minecraft:oxeye_daisy");
      field1.put("minecraft:double_plant.0", "minecraft:sunflower");
      field1.put("minecraft:double_plant.1", "minecraft:lilac");
      field1.put("minecraft:double_plant.2", "minecraft:tall_grass");
      field1.put("minecraft:double_plant.3", "minecraft:large_fern");
      field1.put("minecraft:double_plant.4", "minecraft:rose_bush");
      field1.put("minecraft:double_plant.5", "minecraft:peony");
      field1.put("minecraft:deadbush.0", "minecraft:dead_bush");
      field1.put("minecraft:tallgrass.1", "minecraft:grass");
      field1.put("minecraft:tallgrass.2", "minecraft:fern");
      field1.put("minecraft:sponge.0", "minecraft:sponge");
      field1.put("minecraft:sponge.1", "minecraft:wet_sponge");
      field1.put("minecraft:purpur_slab.0", "minecraft:purpur_slab");
      field1.put("minecraft:stone_slab.0", "minecraft:stone_slab");
      field1.put("minecraft:stone_slab.1", "minecraft:sandstone_slab");
      field1.put("minecraft:stone_slab.2", "minecraft:petrified_oak_slab");
      field1.put("minecraft:stone_slab.3", "minecraft:cobblestone_slab");
      field1.put("minecraft:stone_slab.4", "minecraft:brick_slab");
      field1.put("minecraft:stone_slab.5", "minecraft:stone_brick_slab");
      field1.put("minecraft:stone_slab.6", "minecraft:nether_brick_slab");
      field1.put("minecraft:stone_slab.7", "minecraft:quartz_slab");
      field1.put("minecraft:stone_slab2.0", "minecraft:red_sandstone_slab");
      field1.put("minecraft:wooden_slab.0", "minecraft:oak_slab");
      field1.put("minecraft:wooden_slab.1", "minecraft:spruce_slab");
      field1.put("minecraft:wooden_slab.2", "minecraft:birch_slab");
      field1.put("minecraft:wooden_slab.3", "minecraft:jungle_slab");
      field1.put("minecraft:wooden_slab.4", "minecraft:acacia_slab");
      field1.put("minecraft:wooden_slab.5", "minecraft:dark_oak_slab");
      field1.put("minecraft:coal.0", "minecraft:coal");
      field1.put("minecraft:coal.1", "minecraft:charcoal");
      field1.put("minecraft:fish.0", "minecraft:cod");
      field1.put("minecraft:fish.1", "minecraft:salmon");
      field1.put("minecraft:fish.2", "minecraft:clownfish");
      field1.put("minecraft:fish.3", "minecraft:pufferfish");
      field1.put("minecraft:cooked_fish.0", "minecraft:cooked_cod");
      field1.put("minecraft:cooked_fish.1", "minecraft:cooked_salmon");
      field1.put("minecraft:skull.0", "minecraft:skeleton_skull");
      field1.put("minecraft:skull.1", "minecraft:wither_skeleton_skull");
      field1.put("minecraft:skull.2", "minecraft:zombie_head");
      field1.put("minecraft:skull.3", "minecraft:player_head");
      field1.put("minecraft:skull.4", "minecraft:creeper_head");
      field1.put("minecraft:skull.5", "minecraft:dragon_head");
      field1.put("minecraft:golden_apple.0", "minecraft:golden_apple");
      field1.put("minecraft:golden_apple.1", "minecraft:enchanted_golden_apple");
      field1.put("minecraft:fireworks.0", "minecraft:firework_rocket");
      field1.put("minecraft:firework_charge.0", "minecraft:firework_star");
      field1.put("minecraft:dye.0", "minecraft:ink_sac");
      field1.put("minecraft:dye.1", "minecraft:rose_red");
      field1.put("minecraft:dye.2", "minecraft:cactus_green");
      field1.put("minecraft:dye.3", "minecraft:cocoa_beans");
      field1.put("minecraft:dye.4", "minecraft:lapis_lazuli");
      field1.put("minecraft:dye.5", "minecraft:purple_dye");
      field1.put("minecraft:dye.6", "minecraft:cyan_dye");
      field1.put("minecraft:dye.7", "minecraft:light_gray_dye");
      field1.put("minecraft:dye.8", "minecraft:gray_dye");
      field1.put("minecraft:dye.9", "minecraft:pink_dye");
      field1.put("minecraft:dye.10", "minecraft:lime_dye");
      field1.put("minecraft:dye.11", "minecraft:dandelion_yellow");
      field1.put("minecraft:dye.12", "minecraft:light_blue_dye");
      field1.put("minecraft:dye.13", "minecraft:magenta_dye");
      field1.put("minecraft:dye.14", "minecraft:orange_dye");
      field1.put("minecraft:dye.15", "minecraft:bone_meal");
      field1.put("minecraft:silver_shulker_box.0", "minecraft:light_gray_shulker_box");
      field1.put("minecraft:fence.0", "minecraft:oak_fence");
      field1.put("minecraft:fence_gate.0", "minecraft:oak_fence_gate");
      field1.put("minecraft:wooden_door.0", "minecraft:oak_door");
      field1.put("minecraft:boat.0", "minecraft:oak_boat");
      field1.put("minecraft:lit_pumpkin.0", "minecraft:jack_o_lantern");
      field1.put("minecraft:pumpkin.0", "minecraft:carved_pumpkin");
      field1.put("minecraft:trapdoor.0", "minecraft:oak_trapdoor");
      field1.put("minecraft:nether_brick.0", "minecraft:nether_bricks");
      field1.put("minecraft:red_nether_brick.0", "minecraft:red_nether_bricks");
      field1.put("minecraft:netherbrick.0", "minecraft:nether_brick");
      field1.put("minecraft:wooden_button.0", "minecraft:oak_button");
      field1.put("minecraft:wooden_pressure_plate.0", "minecraft:oak_pressure_plate");
      field1.put("minecraft:noteblock.0", "minecraft:note_block");
      if (Bridge.getMinecraftVersion().method22()) {
         field1.put("minecraft:bed.0", "minecraft:bed");
      } else {
         field1.put("minecraft:bed.0", "minecraft:white_bed");
         field1.put("minecraft:bed.1", "minecraft:orange_bed");
         field1.put("minecraft:bed.2", "minecraft:magenta_bed");
         field1.put("minecraft:bed.3", "minecraft:light_blue_bed");
         field1.put("minecraft:bed.4", "minecraft:yellow_bed");
         field1.put("minecraft:bed.5", "minecraft:lime_bed");
         field1.put("minecraft:bed.6", "minecraft:pink_bed");
         field1.put("minecraft:bed.7", "minecraft:gray_bed");
         field1.put("minecraft:bed.8", "minecraft:light_gray_bed");
         field1.put("minecraft:bed.9", "minecraft:cyan_bed");
         field1.put("minecraft:bed.10", "minecraft:purple_bed");
         field1.put("minecraft:bed.11", "minecraft:blue_bed");
         field1.put("minecraft:bed.12", "minecraft:brown_bed");
         field1.put("minecraft:bed.13", "minecraft:green_bed");
         field1.put("minecraft:bed.14", "minecraft:red_bed");
         field1.put("minecraft:bed.15", "minecraft:black_bed");
      }

      field1.put("minecraft:banner.15", "minecraft:white_banner");
      field1.put("minecraft:banner.14", "minecraft:orange_banner");
      field1.put("minecraft:banner.13", "minecraft:magenta_banner");
      field1.put("minecraft:banner.12", "minecraft:light_blue_banner");
      field1.put("minecraft:banner.11", "minecraft:yellow_banner");
      field1.put("minecraft:banner.10", "minecraft:lime_banner");
      field1.put("minecraft:banner.9", "minecraft:pink_banner");
      field1.put("minecraft:banner.8", "minecraft:gray_banner");
      field1.put("minecraft:banner.7", "minecraft:light_gray_banner");
      field1.put("minecraft:banner.6", "minecraft:cyan_banner");
      field1.put("minecraft:banner.5", "minecraft:purple_banner");
      field1.put("minecraft:banner.4", "minecraft:blue_banner");
      field1.put("minecraft:banner.3", "minecraft:brown_banner");
      field1.put("minecraft:banner.2", "minecraft:green_banner");
      field1.put("minecraft:banner.1", "minecraft:red_banner");
      field1.put("minecraft:banner.0", "minecraft:black_banner");
      field1.put("minecraft:grass.0", "minecraft:grass_block");
      field1.put("minecraft:brick_block.0", "minecraft:bricks");
      field1.put("minecraft:end_bricks.0", "minecraft:end_stone_bricks");
      field1.put("minecraft:golden_rail.0", "minecraft:powered_rail");
      field1.put("minecraft:magma.0", "minecraft:magma_block");
      field1.put("minecraft:quartz_ore.0", "minecraft:nether_quartz_ore");
      field1.put("minecraft:reeds.0", "minecraft:sugar_cane");
      field1.put("minecraft:slime.0", "minecraft:slime_block");
      field1.put("minecraft:stone_stairs.0", "minecraft:cobblestone_stairs");
      field1.put("minecraft:waterlily.0", "minecraft:lily_pad");
      field1.put("minecraft:web.0", "minecraft:cobweb");
      field1.put("minecraft:snow.0", "minecraft:snow_block");
      field1.put("minecraft:snow_layer.0", "minecraft:snow");
      field1.put("minecraft:record_11.0", "minecraft:music_disc_11");
      field1.put("minecraft:record_13.0", "minecraft:music_disc_13");
      field1.put("minecraft:record_blocks.0", "minecraft:music_disc_blocks");
      field1.put("minecraft:record_cat.0", "minecraft:music_disc_cat");
      field1.put("minecraft:record_chirp.0", "minecraft:music_disc_chirp");
      field1.put("minecraft:record_far.0", "minecraft:music_disc_far");
      field1.put("minecraft:record_mall.0", "minecraft:music_disc_mall");
      field1.put("minecraft:record_mellohi.0", "minecraft:music_disc_mellohi");
      field1.put("minecraft:record_stal.0", "minecraft:music_disc_stal");
      field1.put("minecraft:record_strad.0", "minecraft:music_disc_strad");
      field1.put("minecraft:record_wait.0", "minecraft:music_disc_wait");
      field1.put("minecraft:record_ward.0", "minecraft:music_disc_ward");
      field1.forEach((var0, var1) -> {
         String[] var2 = var0.split("\\.");
         String var3 = var2[0];
         int var4 = Integer.parseInt(var2[1]);
         field2.computeIfAbsent(var3, var0x -> new ArrayList<>()).add(new Itemcounter.Data(var1, var4));
      });
   }

   public class Data {
      private final String field1;
      private final int field2;

      public Data(String var1, int var2) {
         this.field1 = var1;
         this.field2 = var2;
      }

      public String method1() {
         return this.field1;
      }

      public int method2() {
         return this.field2;
      }
   }
}
