import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.protobuf.ByteString;
import com.lunarclient.authenticator.v1.AuthSuccessMessage;
import com.lunarclient.common.v1.Color;
import com.lunarclient.websocket.protocol.v1.WebSocketRpcResponse;
import com.lunarclient.websocket.serverdiscovery.v1.AutocompleteSuggestion;
import com.lunarclient.websocket.serverdiscovery.v1.DiscoverServersResponse;
import com.lunarclient.websocket.serverdiscovery.v1.LoadAutocompleteSuggestionsResponse;
import com.lunarclient.websocket.serverdiscovery.v1.LoadServerModalRequest;
import com.lunarclient.websocket.serverdiscovery.v1.LoadServerModalResponse;
import com.lunarclient.websocket.serverdiscovery.v1.SearchServersRequest;
import com.lunarclient.websocket.serverdiscovery.v1.SearchServersResponse;
import com.lunarclient.websocket.serverdiscovery.v1.ServerCard;
import com.lunarclient.websocket.serverdiscovery.v1.ServerGameType;
import com.lunarclient.websocket.serverdiscovery.v1.ServerModalDetails;
import com.lunarclient.websocket.serverdiscovery.v1.ServerSection;
import org.java_websocket.WebSocket;
import org.java_websocket.client.WebSocketClient;
import org.java_websocket.drafts.Draft_6455;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.handshake.ServerHandshake;
import org.java_websocket.server.WebSocketServer;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.InetSocketAddress;
import java.net.URI;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalTime;
import java.util.Base64;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

/**
 * Local stand-ins for Lunar's removed backends, with an official-server proxy.
 *
 *   Authenticator  ws://127.0.0.1:<authPort>/game   -> wss://authenticator.lunarclientprod.com/game
 *   AssetServer    ws://127.0.0.1:<assetPort>/game  -> wss://websocket.lunarclientprod.com/game
 *
 * Behaviour depends on the account that connects (matched in accounts.json):
 *
 *   premium  - the connection is relayed to Lunar's official backend, so the
 *              client sees real Lunar users: tab-list icons, other players'
 *              cosmetics/emotes, friends, server discovery, ...
 *   cracked  - a local answer is generated. The client marks the asset state
 *              READY (no more "Connecting...") and its own cosmetics/emotes/
 *              sprays/badges are all granted via the has-all login flags.
 *
 * If the official backend cannot be reached or rejects a premium session, we
 * fall back to the local behaviour so the game still works offline.
 *
 * Point the client here with (dev build mode only):
 *   -DserviceOverrideAuthenticator=ws://127.0.0.1:<authPort>
 *   -DserviceOverrideAssetServer=ws://127.0.0.1:<assetPort>
 */
public final class FakeBackend {

    private static final String OFFICIAL_AUTH = "wss://authenticator.lunarclientprod.com/game";
    private static final String OFFICIAL_ASSET = "wss://websocket.lunarclientprod.com/game";
    private static final long CONNECT_TIMEOUT_SECONDS = 10L;

    private static PrintWriter log;
    private static Path accountsFile;

    /** Server discovery catalogue generated by tools/fetch_server_mappings.py. */
    private static Discovery discovery = new Discovery();

    /** client connection -> upstream official connection (for relaying). */
    private static final Map<WebSocket, WebSocketClient> relays = new ConcurrentHashMap<>();

    /** username (lowercase) -> premium session authenticated by Lunar. */
    private static final Map<String, Boolean> officialSessions = new ConcurrentHashMap<>();

    public static void main(String[] args) throws Exception {
        int assetPort = args.length > 0 ? Integer.parseInt(args[0]) : 28191;
        int authPort = args.length > 1 ? Integer.parseInt(args[1]) : 28192;
        Path logFile = Paths.get(args.length > 2 ? args[2] : "run/logs/fake-backend.log");
        accountsFile = args.length > 3 ? Paths.get(args[3]) : null;
        Files.createDirectories(logFile.getParent());
        log = new PrintWriter(new FileWriter(logFile.toFile(), true), true);
        discovery = loadDiscovery(args.length > 4 ? Paths.get(args[4]) : null);

        new AuthenticatorServer(authPort).start();
        new AssetServer(assetPort).start();
        line("fake backend listening: authenticator=:" + authPort + " asset=:" + assetPort
                + (accountsFile == null ? "" : " accounts=" + accountsFile));
        line("official proxy: premium accounts -> " + OFFICIAL_AUTH + " / " + OFFICIAL_ASSET);
        Thread.sleep(Long.MAX_VALUE);
    }

    static void line(String text) {
        String msg = "[" + LocalTime.now().withNano(0) + "] " + text;
        System.out.println(msg);
        if (log != null) {
            log.println(msg);
        }
    }

    /** True when accounts.json has this player as a real (non-offline) account. */
    static boolean isPremium(String username) {
        if (username == null || accountsFile == null || !Files.isRegularFile(accountsFile)) {
            return false;
        }
        try {
            String text = new String(Files.readAllBytes(accountsFile), StandardCharsets.UTF_8);
            JsonObject root = new JsonParser().parse(text).getAsJsonObject();
            if (!root.has("accounts")) {
                return false;
            }
            for (Map.Entry<String, JsonElement> entry : root.getAsJsonObject("accounts").entrySet()) {
                JsonObject account = entry.getValue().getAsJsonObject();
                String name = account.has("username") ? account.get("username").getAsString() : "";
                if (!name.equalsIgnoreCase(username)) {
                    continue;
                }
                String token = account.has("accessToken") ? account.get("accessToken").getAsString() : "";
                String refresh = account.has("refreshToken") ? account.get("refreshToken").getAsString() : "";
                return !token.endsWith(".offline") && !refresh.startsWith("local-offline-");
            }
        } catch (Exception exception) {
            line("accounts.json read failed: " + exception);
        }
        return false;
    }

    static void markOfficial(String username) {
        if (username != null) {
            officialSessions.put(username.toLowerCase(), Boolean.TRUE);
        }
    }

    static boolean isOfficial(String username) {
        return username != null && officialSessions.containsKey(username.toLowerCase());
    }

    static byte[] localAuthSuccess(String username) {
        Base64.Encoder encoder = Base64.getUrlEncoder().withoutPadding();
        String header = encoder.encodeToString(
                "{\"alg\":\"none\",\"typ\":\"JWT\"}".getBytes(StandardCharsets.UTF_8));
        long exp = System.currentTimeMillis() / 1000L + 30L * 24L * 3600L;
        String payload = encoder.encodeToString(
                ("{\"sub\":\"" + username + "\",\"name\":\"" + username + "\",\"exp\":" + exp + "}")
                        .getBytes(StandardCharsets.UTF_8));
        String jwt = header + "." + payload + ".local-dev";
        return com.lunarclient.authenticator.v1.ClientboundWebSocketMessage.newBuilder()
                .setAuthSuccess(AuthSuccessMessage.newBuilder().setJwt(jwt).build())
                .build().toByteArray();
    }

    // ------------------------------------------------------------------
    // Server discovery: answer from tools/fake-launcher/discovery.json
    // ------------------------------------------------------------------

    /**
     * The catalogue format is produced by tools/fetch_server_mappings.py from
     * Lunar's official https://servermappings.lunarclientcdn.com/servers.json,
     * so names, addresses, colours and the CDN logo/background URLs are real.
     */
    static final class Discovery {
        final java.util.Map<String, ServerEntry> servers = new java.util.LinkedHashMap<>();
        final java.util.List<SectionEntry> sections = new java.util.ArrayList<>();
        final java.util.List<String> gameTypes = new java.util.ArrayList<>();
        final java.util.Map<String, String> gameTypeIcons = new java.util.LinkedHashMap<>();
        int totalServers;
    }

    static final class ServerEntry {
        String name = "";
        String description = "";
        String primaryAddress = "";
        String primaryColor = "";
        String logoUrl = "";
        String backgroundUrl = "";
        final java.util.List<String> addresses = new java.util.ArrayList<>();
        final java.util.List<String> gameTypes = new java.util.ArrayList<>();
        final java.util.List<String> regions = new java.util.ArrayList<>();
        final java.util.Map<String, String> socials = new java.util.LinkedHashMap<>();
    }

    static final class SectionEntry {
        String id = "";
        String name = "";
        String description = "";
        String cardSize = "medium";
        String emoji = "";
        final java.util.List<String> serverIds = new java.util.ArrayList<>();
    }

    private static Discovery loadDiscovery(Path file) {
        Discovery result = new Discovery();
        if (file == null || !Files.isRegularFile(file)) {
            line("discovery: no catalogue at " + file + ", Discover will be empty");
            return result;
        }
        try {
            String text = new String(Files.readAllBytes(file), StandardCharsets.UTF_8);
            JsonObject root = new JsonParser().parse(text).getAsJsonObject();
            result.totalServers = root.has("totalServers") ? root.get("totalServers").getAsInt() : 0;
            if (root.has("gameTypes")) {
                for (JsonElement element : root.getAsJsonArray("gameTypes")) {
                    JsonObject type = element.getAsJsonObject();
                    String name = type.get("name").getAsString();
                    result.gameTypes.add(name);
                    result.gameTypeIcons.put(name, type.has("emoji") ? type.get("emoji").getAsString() : "");
                }
            }
            if (root.has("sections")) {
                for (JsonElement element : root.getAsJsonArray("sections")) {
                    JsonObject section = element.getAsJsonObject();
                    SectionEntry entry = new SectionEntry();
                    entry.id = section.get("id").getAsString();
                    entry.name = section.get("name").getAsString();
                    entry.description = section.has("description") ? section.get("description").getAsString() : "";
                    entry.cardSize = section.has("cardSize") ? section.get("cardSize").getAsString() : "medium";
                    entry.emoji = section.has("emoji") ? section.get("emoji").getAsString() : "";
                    for (JsonElement id : section.getAsJsonArray("serverIds")) {
                        entry.serverIds.add(id.getAsString());
                    }
                    result.sections.add(entry);
                }
            }
            if (root.has("servers")) {
                for (Map.Entry<String, JsonElement> element : root.getAsJsonObject("servers").entrySet()) {
                    JsonObject server = element.getValue().getAsJsonObject();
                    ServerEntry entry = new ServerEntry();
                    entry.name = server.get("name").getAsString();
                    entry.description = server.has("description") ? server.get("description").getAsString() : "";
                    entry.primaryAddress = server.has("primaryAddress") ? server.get("primaryAddress").getAsString() : "";
                    entry.primaryColor = server.has("primaryColor") ? server.get("primaryColor").getAsString() : "";
                    entry.logoUrl = server.has("logoUrl") && !server.get("logoUrl").isJsonNull()
                            ? server.get("logoUrl").getAsString() : "";
                    entry.backgroundUrl = server.has("backgroundUrl") && !server.get("backgroundUrl").isJsonNull()
                            ? server.get("backgroundUrl").getAsString() : "";
                    addStrings(entry.addresses, server.getAsJsonArray("addresses"));
                    addStrings(entry.gameTypes, server.getAsJsonArray("gameTypes"));
                    addStrings(entry.regions, server.getAsJsonArray("regions"));
                    if (server.has("socials")) {
                        for (Map.Entry<String, JsonElement> social : server.getAsJsonObject("socials").entrySet()) {
                            if (!social.getValue().isJsonNull()) {
                                entry.socials.put(social.getKey(), social.getValue().getAsString());
                            }
                        }
                    }
                    result.servers.put(element.getKey(), entry);
                }
            }
            line("discovery: loaded " + result.servers.size() + " servers / "
                    + result.sections.size() + " sections from " + file);
        } catch (Throwable throwable) {
            line("discovery: failed to read " + file + ": " + throwable);
        }
        return result;
    }

    private static void addStrings(java.util.List<String> target, com.google.gson.JsonArray source) {
        if (source != null) {
            for (JsonElement element : source) {
                target.add(element.getAsString());
            }
        }
    }

    private static ByteString discoveryRpc(String method, ByteString input) {
        // `method` is the lower-cased proto RPC name.
        switch (method) {
            case "login": {
                com.lunarclient.websocket.serverdiscovery.v1.LoginResponse.Builder response =
                        com.lunarclient.websocket.serverdiscovery.v1.LoginResponse.newBuilder()
                                .setTotalServers(discovery.totalServers);
                for (String gameType : discovery.gameTypes) {
                    response.addGameTypes(gameType(gameType));
                }
                return response.build().toByteString();
            }
            case "discoverservers": {
                DiscoverServersResponse.Builder response = DiscoverServersResponse.newBuilder();
                for (SectionEntry section : discovery.sections) {
                    ServerSection.Builder builder = ServerSection.newBuilder()
                            .setId(section.id)
                            .setName(section.name)
                            .setDescription(section.description)
                            .setEmoji(section.emoji)
                            .setCardSize("large".equals(section.cardSize)
                                    ? ServerSection.CardSize.CARD_SIZE_LARGE
                                    : ServerSection.CardSize.CARD_SIZE_MEDIUM);
                    for (String id : section.serverIds) {
                        ServerEntry server = discovery.servers.get(id);
                        if (server == null) {
                            continue;
                        }
                        builder.addCards(card(id, server, "featured".equals(section.id)));
                    }
                    response.addSections(builder);
                }
                return response.build().toByteString();
            }
            case "searchservers": {
                SearchServersRequest request = SearchServersRequest.parseFrom(input);
                String query = request.getQuery().trim().toLowerCase(java.util.Locale.ROOT);
                SearchServersResponse.Builder response = SearchServersResponse.newBuilder();
                if (!query.isEmpty()) {
                    for (Map.Entry<String, ServerEntry> entry : discovery.servers.entrySet()) {
                        if (!matches(entry.getKey(), entry.getValue(), query)) {
                            continue;
                        }
                        response.addServers(card(entry.getKey(), entry.getValue(), false));
                        if (response.getServersCount() >= 30) {
                            break;
                        }
                    }
                }
                return response.build().toByteString();
            }
            case "loadautocompletesuggestions": {
                LoadAutocompleteSuggestionsResponse.Builder response =
                        LoadAutocompleteSuggestionsResponse.newBuilder();
                for (ServerEntry server : discovery.servers.values()) {
                    AutocompleteSuggestion.Builder suggestion = AutocompleteSuggestion.newBuilder()
                            .setName(server.name)
                            .setPrimaryAddress(server.primaryAddress);
                    for (String address : server.addresses) {
                        suggestion.addAddresses(address);
                    }
                    response.addSuggestions(suggestion);
                }
                return response.build().toByteString();
            }
            case "loadservermodal": {
                LoadServerModalRequest request = LoadServerModalRequest.parseFrom(input);
                ServerEntry server = discovery.servers.get(request.getServerMappingsId());
                if (server == null) {
                    return ByteString.EMPTY;
                }
                ServerModalDetails.Builder details = ServerModalDetails.newBuilder()
                        .setDescription(server.description);
                put(details, server.socials, "twitter");
                put(details, server.socials, "discord");
                put(details, server.socials, "youtube");
                put(details, server.socials, "instagram");
                put(details, server.socials, "twitch");
                put(details, server.socials, "telegram");
                put(details, server.socials, "reddit");
                put(details, server.socials, "tiktok");
                put(details, server.socials, "facebook");
                return LoadServerModalResponse.newBuilder().setDetails(details).build().toByteString();
            }
            case "tracksectionnotinterested":
            case "trackserverjoin":
            default:
                return ByteString.EMPTY;
        }
    }

    private static void put(ServerModalDetails.Builder details, Map<String, String> socials, String key) {
        String value = socials.get(key);
        if (value == null || value.isEmpty()) {
            return;
        }
        switch (key) {
            case "twitter" -> details.setTwitter(value);
            case "discord" -> details.setDiscord(value);
            case "youtube" -> details.setYoutube(value);
            case "instagram" -> details.setInstagram(value);
            case "twitch" -> details.setTwitch(value);
            case "telegram" -> details.setTelegram(value);
            case "reddit" -> details.setReddit(value);
            case "tiktok" -> details.setTiktok(value);
            case "facebook" -> details.setFacebook(value);
            default -> {
            }
        }
    }

    private static boolean matches(String id, ServerEntry server, String query) {
        if (id.toLowerCase(java.util.Locale.ROOT).contains(query)
                || server.name.toLowerCase(java.util.Locale.ROOT).contains(query)
                || server.primaryAddress.toLowerCase(java.util.Locale.ROOT).contains(query)) {
            return true;
        }
        for (String address : server.addresses) {
            if (address.toLowerCase(java.util.Locale.ROOT).contains(query)) {
                return true;
            }
        }
        for (String gameType : server.gameTypes) {
            if (gameType.toLowerCase(java.util.Locale.ROOT).contains(query)) {
                return true;
            }
        }
        return false;
    }

    private static ServerGameType gameType(String name) {
        return ServerGameType.newBuilder()
                .setName(name)
                .setEmoji(discovery.gameTypeIcons.getOrDefault(name, ""))
                .build();
    }

    private static ServerCard card(String id, ServerEntry server, boolean featured) {
        ServerCard.Builder builder = ServerCard.newBuilder()
                .setRecommendationId(id)
                .setServerMappingsId(id)
                .setName(server.name)
                .setPrimaryAddress(server.primaryAddress)
                .setBadge(featured ? ServerCard.Badge.BADGE_FEATURED : ServerCard.Badge.BADGE_UNSPECIFIED)
                .addAllRegionCodes(server.regions);
        if (!server.logoUrl.isEmpty()) {
            builder.setLogoUrl(server.logoUrl);
        }
        if (!server.backgroundUrl.isEmpty()) {
            builder.setBackgroundUrl(server.backgroundUrl);
        }
        int color = parseColor(server.primaryColor);
        if (color != 0) {
            builder.setPrimaryColor(Color.newBuilder().setColor(color));
        }
        for (String gameType : server.gameTypes) {
            builder.addGameTypes(gameType(gameType));
        }
        return builder.build();
    }

    /** Stable id for the offline account's default outfit. */
    private static final java.util.UUID LOCAL_OUTFIT_ID =
            java.util.UUID.fromString("00000000-0000-0000-0000-000000000001");

    private static com.lunarclient.common.v1.Uuid localUuid() {
        return uuid(LOCAL_OUTFIT_ID);
    }

    private static com.lunarclient.common.v1.Uuid uuid(java.util.UUID id) {
        return com.lunarclient.common.v1.Uuid.newBuilder()
                .setHigh64(id.getMostSignificantBits())
                .setLow64(id.getLeastSignificantBits())
                .build();
    }

    /** "#RRGGBB" (official mapping format) -> 0xRRGGBB. */
    private static int parseColor(String value) {
        if (value == null || value.isEmpty()) {
            return 0;
        }
        try {
            return Integer.parseInt(value.startsWith("#") ? value.substring(1) : value, 16) & 0xFFFFFF;
        } catch (NumberFormatException ignored) {
            return 0;
        }
    }

    // ------------------------------------------------------------------
    // Authenticator: proxy premium, answer cracked locally
    // ------------------------------------------------------------------

    static final class AuthenticatorServer extends WebSocketServer {

        AuthenticatorServer(int port) {
            super(new InetSocketAddress("127.0.0.1", port));
        }

        @Override
        public void onOpen(WebSocket conn, ClientHandshake handshake) {
            line("auth: connection from " + conn.getRemoteSocketAddress());
        }

        @Override
        public void onClose(WebSocket conn, int code, String reason, boolean remote) {
            line("auth: closed " + code + " " + reason);
            relays.remove(conn);
        }

        @Override
        public void onMessage(WebSocket conn, String message) {
            line("auth: unexpected text frame");
        }

        @Override
        public void onMessage(WebSocket conn, ByteBuffer buffer) {
            byte[] bytes = new byte[buffer.remaining()];
            buffer.duplicate().get(bytes);

            WebSocketClient relay = relays.get(conn);
            if (relay != null) {
                if (relay.isOpen()) {
                    relay.send(bytes);
                } else {
                    relays.remove(conn);
                }
                return;
            }

            com.lunarclient.authenticator.v1.ServerboundWebSocketMessage request;
            try {
                request = com.lunarclient.authenticator.v1.ServerboundWebSocketMessage.parseFrom(bytes);
            } catch (Exception exception) {
                line("auth: unparseable frame (" + bytes.length + "B)");
                return;
            }
            if (!request.hasHello()) {
                line("auth: unhandled " + request.getContentsCase());
                return;
            }
            String username = request.getHello().getIdentity().getUsername();
            if (isPremium(username)) {
                line("auth: " + username + " is premium -> official authenticator");
                final byte[] hello = bytes;
                WebSocketClient upstream = new WebSocketClient(URI.create(OFFICIAL_AUTH), new Draft_6455(),
                        Map.of("Accept", "application/x-protobuf",
                                "User-Agent", "Lunar Client 2.22.35-2637"), 30000) {
                    @Override
                    public void onOpen(ServerHandshake handshake) {
                        line("auth(official): connected, forwarding hello for " + username);
                        send(hello);
                    }

                    @Override
                    public void onMessage(ByteBuffer message) {
                        byte[] copy = new byte[message.remaining()];
                        message.duplicate().get(copy);
                        try {
                            com.lunarclient.authenticator.v1.ClientboundWebSocketMessage inbound =
                                    com.lunarclient.authenticator.v1.ClientboundWebSocketMessage.parseFrom(copy);
                            if (inbound.hasAuthSuccess()) {
                                markOfficial(username);
                                line("auth(official): authSuccess for " + username);
                            }
                        } catch (Exception ignored) {
                            // relay anyway
                        }
                        if (conn.isOpen()) {
                            conn.send(copy);
                        }
                    }

                    @Override
                    public void onMessage(String message) {
                    }

                    @Override
                    public void onClose(int code, String reason, boolean remote) {
                        line("auth(official): closed " + code + " " + reason);
                        relays.remove(conn);
                        if (conn.isOpen() && !isOfficial(username)) {
                            // official auth failed (expired token, no purchase, ...)
                            line("auth: official session failed for " + username + ", fallback local");
                            conn.send(localAuthSuccess(username));
                        }
                    }

                    @Override
                    public void onError(Exception exception) {
                        line("auth(official): error " + exception);
                    }
                };
                relays.put(conn, upstream);
                if (!upstream.connectBlocking(CONNECT_TIMEOUT_SECONDS, TimeUnit.SECONDS)) {
                    line("auth: official connect timed out, fallback local");
                    relays.remove(conn);
                    conn.send(localAuthSuccess(username));
                }
                return;
            }
            line("auth: " + username + " is cracked -> local session");
            conn.send(localAuthSuccess(username));
        }

        @Override
        public void onError(WebSocket conn, Exception exception) {
            line("auth: error " + exception);
        }

        @Override
        public void onStart() {
            line("auth: server started");
        }
    }

    // ------------------------------------------------------------------
    // AssetServer: proxy official sessions, serve local otherwise
    // ------------------------------------------------------------------

    static final class AssetServer extends WebSocketServer {

        AssetServer(int port) {
            super(new InetSocketAddress("127.0.0.1", port));
        }

        @Override
        public void onOpen(WebSocket conn, ClientHandshake handshake) {
            line("asset: connection from " + conn.getRemoteSocketAddress());
        }

        @Override
        public void onClose(WebSocket conn, int code, String reason, boolean remote) {
            line("asset: closed " + code + " " + reason);
            relays.remove(conn);
        }

        @Override
        public void onMessage(WebSocket conn, String message) {
            line("asset: unexpected text frame");
        }

        @Override
        public void onMessage(WebSocket conn, ByteBuffer buffer) {
            byte[] bytes = new byte[buffer.remaining()];
            buffer.duplicate().get(bytes);

            WebSocketClient relay = relays.get(conn);
            if (relay != null) {
                if (relay.isOpen()) {
                    relay.send(bytes);
                } else {
                    relays.remove(conn);
                }
                return;
            }

            if (conn.getAttachment() == null) {
                // first frame: raw Handshake protobuf identifying the player
                String username = null;
                try {
                    com.lunarclient.websocket.handshake.v1.Handshake parsed =
                            com.lunarclient.websocket.handshake.v1.Handshake.parseFrom(bytes);
                    if (parsed.hasIdentity() && parsed.getIdentity().hasPlayer()) {
                        username = parsed.getIdentity().getPlayer().getUsername();
                    }
                } catch (Exception exception) {
                    line("asset: unparsed first frame (" + bytes.length + "B)");
                }
                if (username != null && isOfficial(username)) {
                    line("asset: " + username + " is an official session -> Lunar backend");
                    final byte[] handshake = bytes;
                    final String playerName = username;
                    WebSocketClient upstream = new WebSocketClient(URI.create(OFFICIAL_ASSET), new Draft_6455(),
                            Map.of("Accept", "application/x-protobuf",
                                    "User-Agent", "Lunar Client 2.22.35-2637"), 30000) {
                        @Override
                        public void onOpen(ServerHandshake serverHandshake) {
                            line("asset(official): connected, forwarding handshake for " + playerName);
                            send(handshake);
                        }

                        @Override
                        public void onMessage(ByteBuffer message) {
                            byte[] copy = new byte[message.remaining()];
                            message.duplicate().get(copy);
                            if (conn.isOpen()) {
                                conn.send(copy);
                            }
                        }

                        @Override
                        public void onMessage(String message) {
                        }

                        @Override
                        public void onClose(int code, String reason, boolean remote) {
                            line("asset(official): closed " + code + " " + reason);
                            relays.remove(conn);
                            if (conn.isOpen()) {
                                conn.close(code == 1000 ? 1000 : 1011, reason);
                            }
                        }

                        @Override
                        public void onError(Exception exception) {
                            line("asset(official): error " + exception);
                        }
                    };
                    relays.put(conn, upstream);
                    if (upstream.connectBlocking(CONNECT_TIMEOUT_SECONDS, TimeUnit.SECONDS)) {
                        conn.setAttachment(Boolean.TRUE);
                    } else {
                        line("asset: official connect timed out, serving locally");
                        relays.remove(conn);
                        conn.setAttachment(Boolean.FALSE);
                    }
                    return;
                }
                conn.setAttachment(Boolean.FALSE);
                return; // handshake consumed; local mode
            }

            if (Boolean.TRUE.equals(conn.getAttachment())) {
                return; // relay path handled above
            }

            // ---- local mode ------------------------------------------------
            com.lunarclient.websocket.protocol.v1.ServerboundWebSocketMessage request;
            try {
                request = com.lunarclient.websocket.protocol.v1.ServerboundWebSocketMessage.parseFrom(bytes);
            } catch (Exception exception) {
                line("asset: unparseable frame (" + bytes.length + "B)");
                return;
            }
            String service = request.getService();
            String method = request.getMethod();
            ByteString output = respond(service, method, request.getInput());
            line("asset: local RPC " + shortService(service) + "." + method
                    + " id=" + request.getRequestId().toStringUtf8()
                    + " in=" + request.getInput().size() + "B out=" + output.size() + "B");
            conn.send(com.lunarclient.websocket.protocol.v1.ClientboundWebSocketMessage.newBuilder()
                    .setRpcResponse(WebSocketRpcResponse.newBuilder()
                            .setRequestId(request.getRequestId())
                            .setOutput(output)
                            .build())
                    .build().toByteArray());
        }

        private static ByteString respond(String service, String method, ByteString input) {
            try {
                // The RPC method string keeps the proto name ("Login",
                // "CreateOutfit", ...), so match it case-insensitively: an
                // exact "login" comparison used to fall through and answer
                // EMPTY, which left cosmetics/discovery completely unloaded.
                String rpc = method == null ? "" : method.toLowerCase(java.util.Locale.ROOT);
                if ("lunarclient.websocket.serverdiscovery.v1.ServerDiscoveryService".equals(service)) {
                    return discoveryRpc(rpc, input);
                }
                if ("lunarclient.websocket.cosmetic.v2.CosmeticService".equals(service)) {
                    return cosmeticRpc(rpc, input);
                }
                if (!"login".equals(rpc)) {
                    return ByteString.EMPTY;
                }
                switch (service) {
                    case "lunarclient.websocket.emote.v1.EmoteService":
                        return com.lunarclient.websocket.emote.v1.LoginResponse.newBuilder()
                                .setHasAllEmotesFlag(true)
                                .build().toByteString();
                    case "lunarclient.websocket.spray.v1.SprayService":
                        return com.lunarclient.websocket.spray.v1.LoginResponse.newBuilder()
                                .setHasAllSpraysFlag(true)
                                .build().toByteString();
                    case "lunarclient.websocket.badge.v1.BadgeService":
                        return com.lunarclient.websocket.badge.v1.LoginResponse.newBuilder()
                                .setHasAllBadgesFlag(true)
                                .build().toByteString();
                    case "lunarclient.websocket.store.v1.StoreService":
                        return com.lunarclient.websocket.store.v1.LoginResponse.newBuilder()
                                .setCoins(1000000L)
                                .build().toByteString();
                    default:
                        return ByteString.EMPTY;
                }
            } catch (Throwable throwable) {
                line("asset: response error for " + service + "." + method + ": " + throwable);
                return ByteString.EMPTY;
            }
        }

        /**
         * Local cosmetics: has-all flags plus one editable "Default" outfit.
         *
         * The outfit matters beyond the locker UI: OutfitManager lazily builds
         * a player's conditional outfit tree and reads
         * {@code defaultTree.getCurrentOutfit().getBadgeId()} without checking
         * getCurrentOutfit() for null, so a login response without a default
         * outfit NPEs the moment an outfit is requested (opening the
         * cosmetics drawer does exactly that).
         */
        private static ByteString cosmeticRpc(String method, ByteString input) {
            switch (method) {
                case "login": {
                    com.lunarclient.websocket.cosmetic.v2.Outfit defaultOutfit =
                            com.lunarclient.websocket.cosmetic.v2.Outfit.newBuilder()
                                    .setId(localUuid())
                                    .setName("Default")
                                    .setFavorite(true)
                                    .build();
                    return com.lunarclient.websocket.cosmetic.v2.LoginResponse.newBuilder()
                            .setHasAllCosmeticsFlag(true)
                            .addOutfits(defaultOutfit)
                            .setOutfitTree(com.lunarclient.websocket.cosmetic.v2.OutfitTree.newBuilder()
                                    .setDefaultOutfitId(localUuid())
                                    .build())
                            .build().toByteString();
                }
                case "createoutfit": {
                    com.lunarclient.websocket.cosmetic.v2.CreateOutfitRequest request =
                            com.lunarclient.websocket.cosmetic.v2.CreateOutfitRequest.parseFrom(input);
                    com.lunarclient.websocket.cosmetic.v2.Outfit outfit =
                            com.lunarclient.websocket.cosmetic.v2.Outfit.newBuilder()
                                    .setId(uuid(java.util.UUID.randomUUID()))
                                    .setName(request.getName())
                                    .build();
                    return com.lunarclient.websocket.cosmetic.v2.CreateOutfitResponse.newBuilder()
                            .setStatus(com.lunarclient.websocket.cosmetic.v2.CreateOutfitResponse.Status.STATUS_OK)
                            .setOutfit(outfit)
                            .build().toByteString();
                }
                case "updateoutfit": {
                    com.lunarclient.websocket.cosmetic.v2.UpdateOutfitRequest request =
                            com.lunarclient.websocket.cosmetic.v2.UpdateOutfitRequest.parseFrom(input);
                    return com.lunarclient.websocket.cosmetic.v2.UpdateOutfitResponse.newBuilder()
                            .setStatus(com.lunarclient.websocket.cosmetic.v2.UpdateOutfitResponse.Status.STATUS_OK)
                            .setOutfit(request.getOutfit())
                            .build().toByteString();
                }
                case "deleteoutfit":
                    return com.lunarclient.websocket.cosmetic.v2.DeleteOutfitResponse.newBuilder()
                            .setStatus(com.lunarclient.websocket.cosmetic.v2.DeleteOutfitResponse.Status.STATUS_OK)
                            .build().toByteString();
                case "selectoutfit":
                    return com.lunarclient.websocket.cosmetic.v2.SelectOutfitResponse.newBuilder()
                            .setStatus(com.lunarclient.websocket.cosmetic.v2.SelectOutfitResponse.Status.STATUS_OK)
                            .build().toByteString();
                case "favoritecosmetic":
                case "unfavoritecosmetic":
                    return ByteString.EMPTY;
                default:
                    return ByteString.EMPTY;
            }
        }

        private static String shortService(String service) {
            int index = service.lastIndexOf('.');
            return index == -1 ? service : service.substring(index + 1);
        }

        @Override
        public void onError(WebSocket conn, Exception exception) {
            line("asset: error " + exception);
        }

        @Override
        public void onStart() {
            line("asset: server started");
        }
    }
}
