package com.moonsworth.lunar.icon.mixin;

import com.moonsworth.lunar.bridge.Bridge;
import com.moonsworth.lunar.bridge.Bridge2_39;
import com.moonsworth.lunar.bridge.KeyCode;
import java.util.Locale;
import org.lwjgl.glfw.GLFW;

public class Bridge2Handler implements Bridge2_39 {
   @Override
   public boolean method1(KeyCode var1) {
      if (var1 == KeyCode.KEY_NONE) {
         return false;
      }

      long var2 = Bridge.method9().bridge$getWindowId();
      int var4;
      if (var1.isMouse()) {
         var4 = GLFW.glfwGetMouseButton(var2, method5(var1) + 100);
      } else {
         var4 = GLFW.glfwGetKey(var2, method5(var1));
      }

      return var4 == 1;
   }

   @Override
   public String method2(KeyCode var1) {
      int var2 = method5(var1);
      int var3 = GLFW.glfwGetKeyScancode(var2);
      return GLFW.glfwGetKeyName(var2, var3);
   }

   @Override
   public void method3(boolean var1) {
      if (Bridge.method9() != null) {
         Bridge.method9().bridge$setRepeatEventsEnabled(var1);
      }
   }

   @Override
   public int method4(KeyCode var1) {
      return method5(var1);
   }

   public static int method5(KeyCode var0) {
      switch (var0) {
         case KEY_LCOMMAND:
         case KEY_LWINDOWS:
            return 343;
         case KEY_RCOMMAND:
         case KEY_RWINDOWS:
            return 347;
         case KEY_NONE:
            return -1;
         case KEY_0:
            return 48;
         case KEY_1:
            return 49;
         case KEY_2:
            return 50;
         case KEY_3:
            return 51;
         case KEY_4:
            return 52;
         case KEY_5:
            return 53;
         case KEY_6:
            return 54;
         case KEY_7:
            return 55;
         case KEY_8:
            return 56;
         case KEY_9:
            return 57;
         case KEY_A:
            return 65;
         case KEY_B:
            return 66;
         case KEY_C:
            return 67;
         case KEY_D:
            return 68;
         case KEY_E:
            return 69;
         case KEY_F:
            return 70;
         case KEY_G:
            return 71;
         case KEY_H:
            return 72;
         case KEY_I:
            return 73;
         case KEY_J:
            return 74;
         case KEY_K:
            return 75;
         case KEY_L:
            return 76;
         case KEY_M:
            return 77;
         case KEY_N:
            return 78;
         case KEY_O:
            return 79;
         case KEY_P:
            return 80;
         case KEY_Q:
            return 81;
         case KEY_R:
            return 82;
         case KEY_S:
            return 83;
         case KEY_T:
            return 84;
         case KEY_U:
            return 85;
         case KEY_V:
            return 86;
         case KEY_W:
            return 87;
         case KEY_X:
            return 88;
         case KEY_Y:
            return 89;
         case KEY_Z:
            return 90;
         case KEY_CLEAR:
            return 218;
         case KEY_RSHIFT:
            return 344;
         case KEY_LSHIFT:
            return 340;
         case KEY_RMENU:
            return 346;
         case KEY_LMENU:
            return 342;
         case KEY_LCONTROL:
            return 341;
         case KEY_RETURN:
            return 257;
         case KEY_ESCAPE:
            return 256;
         case KEY_TAB:
            return 258;
         case KEY_GRAVE:
            return 96;
         case KEY_UP:
            return 265;
         case KEY_DOWN:
            return 264;
         case KEY_LEFT:
            return 263;
         case KEY_RIGHT:
            return 262;
         case KEY_HOME:
            return 268;
         case KEY_END:
            return 269;
         case KEY_DELETE:
            return 261;
         case KEY_BACK:
            return 259;
         case KEY_F1:
            return 290;
         case KEY_F2:
            return 291;
         case KEY_F3:
            return 292;
         case KEY_F4:
            return 293;
         case KEY_F5:
            return 294;
         case KEY_F6:
            return 295;
         case KEY_F7:
            return 296;
         case KEY_F8:
            return 297;
         case KEY_F9:
            return 298;
         case KEY_F10:
            return 299;
         case KEY_F11:
            return 300;
         case KEY_F12:
            return 301;
         case KEY_MINUS:
            return 45;
         case KEY_EQUALS:
            return 61;
         case KEY_LBRACKET:
            return 91;
         case KEY_RBRACKET:
            return 93;
         case KEY_SEMICOLON:
            return 59;
         case KEY_APOSTROPHE:
            return 39;
         case KEY_BACKSLASH:
            return 92;
         case KEY_COMMA:
            return 44;
         case KEY_PERIOD:
            return 46;
         case KEY_SLASH:
            return 47;
         case KEY_MULTIPLY:
            return 332;
         case KEY_CAPITAL:
            return 280;
         case KEY_NUMLOCK:
            return 282;
         case KEY_SCROLL:
            return 281;
         case KEY_NUMPAD7:
            return 327;
         case KEY_NUMPAD8:
            return 328;
         case KEY_NUMPAD9:
            return 329;
         case KEY_SUBTRACT:
            return 333;
         case KEY_NUMPAD4:
            return 324;
         case KEY_NUMPAD5:
            return 325;
         case KEY_NUMPAD6:
            return 326;
         case KEY_ADD:
            return 334;
         case KEY_NUMPAD1:
            return 321;
         case KEY_NUMPAD2:
            return 322;
         case KEY_NUMPAD3:
            return 323;
         case KEY_NUMPAD0:
            return 320;
         case KEY_DECIMAL:
            return 330;
         case KEY_F13:
            return 302;
         case KEY_F14:
            return 303;
         case KEY_F15:
            return 304;
         case KEY_F16:
            return 305;
         case KEY_F17:
            return 306;
         case KEY_F18:
            return 307;
         case KEY_F19:
            return 308;
         case KEY_NUMPADEQUALS:
            return 336;
         case KEY_NUMPADENTER:
            return 335;
         case KEY_DIVIDE:
            return 331;
         case KEY_PAUSE:
            return 284;
         case KEY_INSERT:
            return 260;
         case KEY_SPACE:
            return 32;
         case KEY_RCONTROL:
            return 345;
         case KEY_MOUSE1:
            return -100;
         case KEY_MOUSE2:
            return -99;
         case KEY_MOUSE3:
            return -98;
         case KEY_MOUSE4:
            return -97;
         case KEY_MOUSE5:
            return -96;
         case KEY_PGUP:
            return 266;
         case KEY_PGDOWN:
            return 267;
         case KEY_PG:
            return 221;
         case KEY_PRINTSC:
            return 283;
         default:
            System.err.println("Can't translate key " + var0.name());
            return -1;
      }
   }

   public static KeyCode method6(int var0) {
      switch (var0) {
         case -100:
            return KeyCode.KEY_MOUSE1;
         case -99:
            return KeyCode.KEY_MOUSE2;
         case -98:
            return KeyCode.KEY_MOUSE3;
         case -97:
            return KeyCode.KEY_MOUSE4;
         case -96:
            return KeyCode.KEY_MOUSE5;
         case -95:
         case -94:
         case -93:
         case -92:
         case -91:
         case -90:
         case -89:
         case -88:
         case -87:
         case -86:
         case -85:
         case -84:
         case -83:
         case -82:
         case -81:
         case -80:
         case -79:
         case -78:
         case -77:
         case -76:
         case -75:
         case -74:
         case -73:
         case -72:
         case -71:
         case -70:
         case -69:
         case -68:
         case -67:
         case -66:
         case -65:
         case -64:
         case -63:
         case -62:
         case -61:
         case -60:
         case -59:
         case -58:
         case -57:
         case -56:
         case -55:
         case -54:
         case -53:
         case -52:
         case -51:
         case -50:
         case -49:
         case -48:
         case -47:
         case -46:
         case -45:
         case -44:
         case -43:
         case -42:
         case -41:
         case -40:
         case -39:
         case -38:
         case -37:
         case -36:
         case -35:
         case -34:
         case -33:
         case -32:
         case -31:
         case -30:
         case -29:
         case -28:
         case -27:
         case -26:
         case -25:
         case -24:
         case -23:
         case -22:
         case -21:
         case -20:
         case -19:
         case -18:
         case -17:
         case -16:
         case -15:
         case -14:
         case -13:
         case -12:
         case -11:
         case -10:
         case -9:
         case -8:
         case -7:
         case -6:
         case -5:
         case -4:
         case -3:
         case -2:
         case 1:
         case 2:
         case 3:
         case 4:
         case 5:
         case 6:
         case 7:
         case 8:
         case 9:
         case 10:
         case 11:
         case 12:
         case 13:
         case 14:
         case 15:
         case 16:
         case 17:
         case 18:
         case 19:
         case 20:
         case 21:
         case 22:
         case 23:
         case 24:
         case 25:
         case 26:
         case 27:
         case 28:
         case 29:
         case 30:
         case 31:
         case 33:
         case 34:
         case 35:
         case 36:
         case 37:
         case 38:
         case 40:
         case 41:
         case 42:
         case 43:
         case 58:
         case 60:
         case 62:
         case 63:
         case 64:
         case 94:
         case 95:
         case 97:
         case 98:
         case 99:
         case 100:
         case 101:
         case 102:
         case 103:
         case 104:
         case 105:
         case 106:
         case 107:
         case 108:
         case 109:
         case 110:
         case 111:
         case 112:
         case 113:
         case 114:
         case 115:
         case 116:
         case 117:
         case 118:
         case 119:
         case 120:
         case 121:
         case 122:
         case 123:
         case 124:
         case 125:
         case 126:
         case 127:
         case 128:
         case 129:
         case 130:
         case 131:
         case 132:
         case 133:
         case 134:
         case 135:
         case 136:
         case 137:
         case 138:
         case 139:
         case 140:
         case 141:
         case 142:
         case 143:
         case 144:
         case 145:
         case 146:
         case 147:
         case 148:
         case 149:
         case 150:
         case 151:
         case 152:
         case 153:
         case 154:
         case 155:
         case 156:
         case 157:
         case 158:
         case 159:
         case 160:
         case 161:
         case 162:
         case 163:
         case 164:
         case 165:
         case 166:
         case 167:
         case 168:
         case 169:
         case 170:
         case 171:
         case 172:
         case 173:
         case 174:
         case 175:
         case 176:
         case 177:
         case 178:
         case 179:
         case 180:
         case 181:
         case 182:
         case 183:
         case 184:
         case 185:
         case 186:
         case 187:
         case 188:
         case 189:
         case 190:
         case 191:
         case 192:
         case 193:
         case 194:
         case 195:
         case 196:
         case 197:
         case 198:
         case 199:
         case 200:
         case 201:
         case 202:
         case 203:
         case 204:
         case 205:
         case 206:
         case 207:
         case 208:
         case 209:
         case 210:
         case 211:
         case 212:
         case 213:
         case 214:
         case 215:
         case 216:
         case 217:
         case 219:
         case 220:
         case 222:
         case 223:
         case 224:
         case 225:
         case 226:
         case 227:
         case 228:
         case 229:
         case 230:
         case 231:
         case 232:
         case 233:
         case 234:
         case 235:
         case 236:
         case 237:
         case 238:
         case 239:
         case 240:
         case 241:
         case 242:
         case 243:
         case 244:
         case 245:
         case 246:
         case 247:
         case 248:
         case 249:
         case 250:
         case 251:
         case 252:
         case 253:
         case 254:
         case 255:
         case 270:
         case 271:
         case 272:
         case 273:
         case 274:
         case 275:
         case 276:
         case 277:
         case 278:
         case 279:
         case 285:
         case 286:
         case 287:
         case 288:
         case 289:
         case 309:
         case 310:
         case 311:
         case 312:
         case 313:
         case 314:
         case 315:
         case 316:
         case 317:
         case 318:
         case 319:
         case 337:
         case 338:
         case 339:
         default:
            System.err.println("Can't translate key " + var0);
         case 0:
            return KeyCode.KEY_NONE;
         case -1:
            return KeyCode.KEY_NONE;
         case 32:
            return KeyCode.KEY_SPACE;
         case 39:
            return KeyCode.KEY_APOSTROPHE;
         case 44:
            return KeyCode.KEY_COMMA;
         case 45:
            return KeyCode.KEY_MINUS;
         case 46:
            return KeyCode.KEY_PERIOD;
         case 47:
            return KeyCode.KEY_SLASH;
         case 48:
            return KeyCode.KEY_0;
         case 49:
            return KeyCode.KEY_1;
         case 50:
            return KeyCode.KEY_2;
         case 51:
            return KeyCode.KEY_3;
         case 52:
            return KeyCode.KEY_4;
         case 53:
            return KeyCode.KEY_5;
         case 54:
            return KeyCode.KEY_6;
         case 55:
            return KeyCode.KEY_7;
         case 56:
            return KeyCode.KEY_8;
         case 57:
            return KeyCode.KEY_9;
         case 59:
            return KeyCode.KEY_SEMICOLON;
         case 61:
            return KeyCode.KEY_EQUALS;
         case 65:
            return KeyCode.KEY_A;
         case 66:
            return KeyCode.KEY_B;
         case 67:
            return KeyCode.KEY_C;
         case 68:
            return KeyCode.KEY_D;
         case 69:
            return KeyCode.KEY_E;
         case 70:
            return KeyCode.KEY_F;
         case 71:
            return KeyCode.KEY_G;
         case 72:
            return KeyCode.KEY_H;
         case 73:
            return KeyCode.KEY_I;
         case 74:
            return KeyCode.KEY_J;
         case 75:
            return KeyCode.KEY_K;
         case 76:
            return KeyCode.KEY_L;
         case 77:
            return KeyCode.KEY_M;
         case 78:
            return KeyCode.KEY_N;
         case 79:
            return KeyCode.KEY_O;
         case 80:
            return KeyCode.KEY_P;
         case 81:
            return KeyCode.KEY_Q;
         case 82:
            return KeyCode.KEY_R;
         case 83:
            return KeyCode.KEY_S;
         case 84:
            return KeyCode.KEY_T;
         case 85:
            return KeyCode.KEY_U;
         case 86:
            return KeyCode.KEY_V;
         case 87:
            return KeyCode.KEY_W;
         case 88:
            return KeyCode.KEY_X;
         case 89:
            return KeyCode.KEY_Y;
         case 90:
            return KeyCode.KEY_Z;
         case 91:
            return KeyCode.KEY_LBRACKET;
         case 92:
            return KeyCode.KEY_BACKSLASH;
         case 93:
            return KeyCode.KEY_RBRACKET;
         case 96:
            return KeyCode.KEY_GRAVE;
         case 218:
            return KeyCode.KEY_CLEAR;
         case 221:
            return KeyCode.KEY_PG;
         case 256:
            return KeyCode.KEY_ESCAPE;
         case 257:
            return KeyCode.KEY_RETURN;
         case 258:
            return KeyCode.KEY_TAB;
         case 259:
            return KeyCode.KEY_BACK;
         case 260:
            return KeyCode.KEY_INSERT;
         case 261:
            return KeyCode.KEY_DELETE;
         case 262:
            return KeyCode.KEY_RIGHT;
         case 263:
            return KeyCode.KEY_LEFT;
         case 264:
            return KeyCode.KEY_DOWN;
         case 265:
            return KeyCode.KEY_UP;
         case 266:
            return KeyCode.KEY_PGUP;
         case 267:
            return KeyCode.KEY_PGDOWN;
         case 268:
            return KeyCode.KEY_HOME;
         case 269:
            return KeyCode.KEY_END;
         case 280:
            return KeyCode.KEY_CAPITAL;
         case 281:
            return KeyCode.KEY_SCROLL;
         case 282:
            return KeyCode.KEY_NUMLOCK;
         case 283:
            return KeyCode.KEY_PRINTSC;
         case 284:
            return KeyCode.KEY_PAUSE;
         case 290:
            return KeyCode.KEY_F1;
         case 291:
            return KeyCode.KEY_F2;
         case 292:
            return KeyCode.KEY_F3;
         case 293:
            return KeyCode.KEY_F4;
         case 294:
            return KeyCode.KEY_F5;
         case 295:
            return KeyCode.KEY_F6;
         case 296:
            return KeyCode.KEY_F7;
         case 297:
            return KeyCode.KEY_F8;
         case 298:
            return KeyCode.KEY_F9;
         case 299:
            return KeyCode.KEY_F10;
         case 300:
            return KeyCode.KEY_F11;
         case 301:
            return KeyCode.KEY_F12;
         case 302:
            return KeyCode.KEY_F13;
         case 303:
            return KeyCode.KEY_F14;
         case 304:
            return KeyCode.KEY_F15;
         case 305:
            return KeyCode.KEY_F16;
         case 306:
            return KeyCode.KEY_F17;
         case 307:
            return KeyCode.KEY_F18;
         case 308:
            return KeyCode.KEY_F19;
         case 320:
            return KeyCode.KEY_NUMPAD0;
         case 321:
            return KeyCode.KEY_NUMPAD1;
         case 322:
            return KeyCode.KEY_NUMPAD2;
         case 323:
            return KeyCode.KEY_NUMPAD3;
         case 324:
            return KeyCode.KEY_NUMPAD4;
         case 325:
            return KeyCode.KEY_NUMPAD5;
         case 326:
            return KeyCode.KEY_NUMPAD6;
         case 327:
            return KeyCode.KEY_NUMPAD7;
         case 328:
            return KeyCode.KEY_NUMPAD8;
         case 329:
            return KeyCode.KEY_NUMPAD9;
         case 330:
            return KeyCode.KEY_DECIMAL;
         case 331:
            return KeyCode.KEY_DIVIDE;
         case 332:
            return KeyCode.KEY_MULTIPLY;
         case 333:
            return KeyCode.KEY_SUBTRACT;
         case 334:
            return KeyCode.KEY_ADD;
         case 335:
            return KeyCode.KEY_NUMPADENTER;
         case 336:
            return KeyCode.KEY_NUMPADEQUALS;
         case 340:
            return KeyCode.KEY_LSHIFT;
         case 341:
            return KeyCode.KEY_LCONTROL;
         case 342:
            return KeyCode.KEY_LMENU;
         case 343:
            if (System.getProperty("os.name").toLowerCase(Locale.ROOT).contains("mac")) {
               return KeyCode.KEY_LCOMMAND;
            }

            return KeyCode.KEY_LWINDOWS;
         case 344:
            return KeyCode.KEY_RSHIFT;
         case 345:
            return KeyCode.KEY_RCONTROL;
         case 346:
            return KeyCode.KEY_RMENU;
         case 347:
            return System.getProperty("os.name").toLowerCase(Locale.ROOT).contains("mac") ? KeyCode.KEY_RCOMMAND : KeyCode.KEY_RWINDOWS;
      }
   }
}
