package com.moonsworth.lunar.legacy;

import com.moonsworth.lunar.bridge.KeyboardBridge;
import com.moonsworth.lunar.bridge.KeyCode;
import java.util.Locale;
import org.lwjgl.input.Keyboard;
import org.lwjgl.input.Mouse;

public class KeyboardBridgeImpl implements KeyboardBridge {
   public KeyboardBridgeImpl() {
   }

   public boolean method1(KeyCode bridgetype_81) {
      if (bridgetype_81 == KeyCode.KEY_NONE) {
         return false;
      }

      int number2 = method6(bridgetype_81);
      return number2 < 0 ? Mouse.isButtonDown(number2 + 100) : Keyboard.isKeyDown(method6(bridgetype_81));
   }

   public String method2(KeyCode bridgetype_81) {
      return Keyboard.getKeyName(method6(bridgetype_81));
   }

   public void method3(boolean flag1) {
      Keyboard.enableRepeatEvents(flag1);
   }

   public int method4(KeyCode bridgetype_81) {
      return method6(bridgetype_81);
   }

   public static int method5() {
      int number0 = MouseBridgeImpl.method2();
      if (Keyboard.isKeyDown(219) || Keyboard.isKeyDown(220)) {
         number0 |= 8;
      }

      if (Keyboard.isKeyDown(58)) {
         number0 |= 16;
      }

      if (Keyboard.isKeyDown(69)) {
         number0 |= 32;
      }

      return number0;
   }

   // $VF: Unable to simplify switch on enum
   // Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
   public static int method6(KeyCode bridgetype_80) {
      switch (this.field1[bridgetype_80.ordinal()]) {
         case 1:
         case 2:
            return 219;
         case 3:
         case 4:
            return 220;
         case 5:
            return 0;
         case 6:
            return 11;
         case 7:
            return 2;
         case 8:
            return 3;
         case 9:
            return 4;
         case 10:
            return 5;
         case 11:
            return 6;
         case 12:
            return 7;
         case 13:
            return 8;
         case 14:
            return 9;
         case 15:
            return 10;
         case 16:
            return 30;
         case 17:
            return 48;
         case 18:
            return 46;
         case 19:
            return 32;
         case 20:
            return 18;
         case 21:
            return 33;
         case 22:
            return 34;
         case 23:
            return 35;
         case 24:
            return 23;
         case 25:
            return 36;
         case 26:
            return 37;
         case 27:
            return 38;
         case 28:
            return 50;
         case 29:
            return 49;
         case 30:
            return 24;
         case 31:
            return 25;
         case 32:
            return 16;
         case 33:
            return 19;
         case 34:
            return 31;
         case 35:
            return 20;
         case 36:
            return 22;
         case 37:
            return 47;
         case 38:
            return 17;
         case 39:
            return 45;
         case 40:
            return 21;
         case 41:
            return 44;
         case 42:
            return 196;
         case 43:
            return 184;
         case 44:
            return 56;
         case 45:
            return 29;
         case 46:
            return 54;
         case 47:
            return 42;
         case 48:
            return 28;
         case 49:
            return 1;
         case 50:
            return 15;
         case 51:
            return 200;
         case 52:
            return 14;
         case 53:
            return 203;
         case 54:
            return 205;
         case 55:
            return 201;
         case 56:
            return 209;
         case 57:
            return 221;
         case 58:
            return 183;
         case 59:
            return 199;
         case 60:
            return 207;
         case 61:
            return 211;
         case 62:
            return 208;
         case 63:
            return 59;
         case 64:
            return 60;
         case 65:
            return 61;
         case 66:
            return 62;
         case 67:
            return 63;
         case 68:
            return 64;
         case 69:
            return 65;
         case 70:
            return 66;
         case 71:
            return 67;
         case 72:
            return 68;
         case 73:
            return 87;
         case 74:
            return 88;
         case 75:
            return 57;
         case 76:
            return 41;
         case 77:
            return 12;
         case 78:
            return 13;
         case 79:
            return 26;
         case 80:
            return 27;
         case 81:
            return 39;
         case 82:
            return 40;
         case 83:
            return 43;
         case 84:
            return 51;
         case 85:
            return 52;
         case 86:
            return 53;
         case 87:
            return 55;
         case 88:
            return 58;
         case 89:
            return 69;
         case 90:
            return 70;
         case 91:
            return 71;
         case 92:
            return 72;
         case 93:
            return 73;
         case 94:
            return 74;
         case 95:
            return 75;
         case 96:
            return 76;
         case 97:
            return 77;
         case 98:
            return 78;
         case 99:
            return 79;
         case 100:
            return 80;
         case 101:
            return 81;
         case 102:
            return 82;
         case 103:
            return 83;
         case 104:
            return 100;
         case 105:
            return 101;
         case 106:
            return 102;
         case 107:
            return 103;
         case 108:
            return 104;
         case 109:
            return 105;
         case 110:
            return 113;
         case 111:
            return 218;
         case 112:
            return 141;
         case 113:
            return 156;
         case 114:
            return 181;
         case 115:
            return 197;
         case 116:
            return 210;
         case 117:
            return 157;
         case 118:
            return -100;
         case 119:
            return -99;
         case 120:
            return -98;
         case 121:
            return -97;
         case 122:
            return -96;
         default:
            System.err.println("Can't translate key " + bridgetype_80.name());
            return 0;
      }
   }

   public static KeyCode method7(int number0) {
      switch (number0) {
         case -100:
            return KeyCode.KEY_MOUSE1;
         case -99:
            return KeyCode.KEY_MOUSE2;
         case -98:
            return KeyCode.KEY_MOUSE3;
         case -97:
            return KeyCode.KEY_MOUSE4;
         case -96:
            return KeyCode.KEY_MOUSE5;
         case -95:
         case -94:
         case -93:
         case -92:
         case -91:
         case -90:
         case -89:
         case -88:
         case -87:
         case -86:
         case -85:
         case -84:
         case -83:
         case -82:
         case -81:
         case -80:
         case -79:
         case -78:
         case -77:
         case -76:
         case -75:
         case -74:
         case -73:
         case -72:
         case -71:
         case -70:
         case -69:
         case -68:
         case -67:
         case -66:
         case -65:
         case -64:
         case -63:
         case -62:
         case -61:
         case -60:
         case -59:
         case -58:
         case -57:
         case -56:
         case -55:
         case -54:
         case -53:
         case -52:
         case -51:
         case -50:
         case -49:
         case -48:
         case -47:
         case -46:
         case -45:
         case -44:
         case -43:
         case -42:
         case -41:
         case -40:
         case -39:
         case -38:
         case -37:
         case -36:
         case -35:
         case -34:
         case -33:
         case -32:
         case -31:
         case -30:
         case -29:
         case -28:
         case -27:
         case -26:
         case -25:
         case -24:
         case -23:
         case -22:
         case -21:
         case -20:
         case -19:
         case -18:
         case -17:
         case -16:
         case -15:
         case -14:
         case -13:
         case -12:
         case -11:
         case -10:
         case -9:
         case -8:
         case -7:
         case -6:
         case -5:
         case -4:
         case -3:
         case -2:
         case -1:
         case 84:
         case 85:
         case 86:
         case 89:
         case 90:
         case 91:
         case 92:
         case 93:
         case 94:
         case 95:
         case 96:
         case 97:
         case 98:
         case 99:
         case 106:
         case 107:
         case 108:
         case 109:
         case 110:
         case 111:
         case 112:
         case 114:
         case 115:
         case 116:
         case 117:
         case 118:
         case 119:
         case 120:
         case 121:
         case 122:
         case 123:
         case 124:
         case 125:
         case 126:
         case 127:
         case 128:
         case 129:
         case 130:
         case 131:
         case 132:
         case 133:
         case 134:
         case 135:
         case 136:
         case 137:
         case 138:
         case 139:
         case 140:
         case 142:
         case 143:
         case 144:
         case 145:
         case 146:
         case 147:
         case 148:
         case 149:
         case 150:
         case 151:
         case 152:
         case 153:
         case 154:
         case 155:
         case 158:
         case 159:
         case 160:
         case 161:
         case 162:
         case 163:
         case 164:
         case 165:
         case 166:
         case 167:
         case 168:
         case 169:
         case 170:
         case 171:
         case 172:
         case 173:
         case 174:
         case 175:
         case 176:
         case 177:
         case 178:
         case 179:
         case 180:
         case 182:
         case 185:
         case 186:
         case 187:
         case 188:
         case 189:
         case 190:
         case 191:
         case 192:
         case 193:
         case 194:
         case 195:
         case 198:
         case 202:
         case 204:
         case 206:
         case 212:
         case 213:
         case 214:
         case 215:
         case 216:
         case 217:
         default:
            System.err.println("Can't translate key " + number0);
            return KeyCode.KEY_NONE;
         case 0:
            return KeyCode.KEY_NONE;
         case 1:
            return KeyCode.KEY_ESCAPE;
         case 2:
            return KeyCode.KEY_1;
         case 3:
            return KeyCode.KEY_2;
         case 4:
            return KeyCode.KEY_3;
         case 5:
            return KeyCode.KEY_4;
         case 6:
            return KeyCode.KEY_5;
         case 7:
            return KeyCode.KEY_6;
         case 8:
            return KeyCode.KEY_7;
         case 9:
            return KeyCode.KEY_8;
         case 10:
            return KeyCode.KEY_9;
         case 11:
            return KeyCode.KEY_0;
         case 12:
            return KeyCode.KEY_MINUS;
         case 13:
            return KeyCode.KEY_EQUALS;
         case 14:
            return KeyCode.KEY_BACK;
         case 15:
            return KeyCode.KEY_TAB;
         case 16:
            return KeyCode.KEY_Q;
         case 17:
            return KeyCode.KEY_W;
         case 18:
            return KeyCode.KEY_E;
         case 19:
            return KeyCode.KEY_R;
         case 20:
            return KeyCode.KEY_T;
         case 21:
            return KeyCode.KEY_Y;
         case 22:
            return KeyCode.KEY_U;
         case 23:
            return KeyCode.KEY_I;
         case 24:
            return KeyCode.KEY_O;
         case 25:
            return KeyCode.KEY_P;
         case 26:
            return KeyCode.KEY_LBRACKET;
         case 27:
            return KeyCode.KEY_RBRACKET;
         case 28:
            return KeyCode.KEY_RETURN;
         case 29:
            return KeyCode.KEY_LCONTROL;
         case 30:
            return KeyCode.KEY_A;
         case 31:
            return KeyCode.KEY_S;
         case 32:
            return KeyCode.KEY_D;
         case 33:
            return KeyCode.KEY_F;
         case 34:
            return KeyCode.KEY_G;
         case 35:
            return KeyCode.KEY_H;
         case 36:
            return KeyCode.KEY_J;
         case 37:
            return KeyCode.KEY_K;
         case 38:
            return KeyCode.KEY_L;
         case 39:
            return KeyCode.KEY_SEMICOLON;
         case 40:
            return KeyCode.KEY_APOSTROPHE;
         case 41:
            return KeyCode.KEY_GRAVE;
         case 42:
            return KeyCode.KEY_LSHIFT;
         case 43:
            return KeyCode.KEY_BACKSLASH;
         case 44:
            return KeyCode.KEY_Z;
         case 45:
            return KeyCode.KEY_X;
         case 46:
            return KeyCode.KEY_C;
         case 47:
            return KeyCode.KEY_V;
         case 48:
            return KeyCode.KEY_B;
         case 49:
            return KeyCode.KEY_N;
         case 50:
            return KeyCode.KEY_M;
         case 51:
            return KeyCode.KEY_COMMA;
         case 52:
            return KeyCode.KEY_PERIOD;
         case 53:
            return KeyCode.KEY_SLASH;
         case 54:
            return KeyCode.KEY_RSHIFT;
         case 55:
            return KeyCode.KEY_MULTIPLY;
         case 56:
            return KeyCode.KEY_LMENU;
         case 57:
            return KeyCode.KEY_SPACE;
         case 58:
            return KeyCode.KEY_CAPITAL;
         case 59:
            return KeyCode.KEY_F1;
         case 60:
            return KeyCode.KEY_F2;
         case 61:
            return KeyCode.KEY_F3;
         case 62:
            return KeyCode.KEY_F4;
         case 63:
            return KeyCode.KEY_F5;
         case 64:
            return KeyCode.KEY_F6;
         case 65:
            return KeyCode.KEY_F7;
         case 66:
            return KeyCode.KEY_F8;
         case 67:
            return KeyCode.KEY_F9;
         case 68:
            return KeyCode.KEY_F10;
         case 69:
            return KeyCode.KEY_NUMLOCK;
         case 70:
            return KeyCode.KEY_SCROLL;
         case 71:
            return KeyCode.KEY_NUMPAD7;
         case 72:
            return KeyCode.KEY_NUMPAD8;
         case 73:
            return KeyCode.KEY_NUMPAD9;
         case 74:
            return KeyCode.KEY_SUBTRACT;
         case 75:
            return KeyCode.KEY_NUMPAD4;
         case 76:
            return KeyCode.KEY_NUMPAD5;
         case 77:
            return KeyCode.KEY_NUMPAD6;
         case 78:
            return KeyCode.KEY_ADD;
         case 79:
            return KeyCode.KEY_NUMPAD1;
         case 80:
            return KeyCode.KEY_NUMPAD2;
         case 81:
            return KeyCode.KEY_NUMPAD3;
         case 82:
            return KeyCode.KEY_NUMPAD0;
         case 83:
            return KeyCode.KEY_DECIMAL;
         case 87:
            return KeyCode.KEY_F11;
         case 88:
            return KeyCode.KEY_F12;
         case 100:
            return KeyCode.KEY_F13;
         case 101:
            return KeyCode.KEY_F14;
         case 102:
            return KeyCode.KEY_F15;
         case 103:
            return KeyCode.KEY_F16;
         case 104:
            return KeyCode.KEY_F17;
         case 105:
            return KeyCode.KEY_F18;
         case 113:
            return KeyCode.KEY_F19;
         case 141:
            return KeyCode.KEY_NUMPADEQUALS;
         case 156:
            return KeyCode.KEY_NUMPADENTER;
         case 157:
            return KeyCode.KEY_RCONTROL;
         case 181:
            return KeyCode.KEY_DIVIDE;
         case 183:
            return KeyCode.KEY_PRINTSC;
         case 184:
            return KeyCode.KEY_RMENU;
         case 196:
            return KeyCode.KEY_FUNCTION;
         case 197:
            return KeyCode.KEY_PAUSE;
         case 199:
            return KeyCode.KEY_HOME;
         case 200:
            return KeyCode.KEY_UP;
         case 201:
            return KeyCode.KEY_PGUP;
         case 203:
            return KeyCode.KEY_LEFT;
         case 205:
            return KeyCode.KEY_RIGHT;
         case 207:
            return KeyCode.KEY_END;
         case 208:
            return KeyCode.KEY_DOWN;
         case 209:
            return KeyCode.KEY_PGDOWN;
         case 210:
            return KeyCode.KEY_INSERT;
         case 211:
            return KeyCode.KEY_DELETE;
         case 218:
            return KeyCode.KEY_CLEAR;
         case 219:
            if (System.getProperty("os.name").toLowerCase(Locale.ROOT).contains("mac")) {
               return KeyCode.KEY_LCOMMAND;
            }

            return KeyCode.KEY_LWINDOWS;
         case 220:
            if (System.getProperty("os.name").toLowerCase(Locale.ROOT).contains("mac")) {
               return KeyCode.KEY_RCOMMAND;
            }

            return KeyCode.KEY_RWINDOWS;
         case 221:
            return KeyCode.KEY_PG;
      }
   }
}
