package com.moonsworth.lunar.client.framework.feature.mod.fishing.click;

import lombok.Generated;

public final class FontGlyphs {
   public static final char GLYPH_HASH = '\ue000';
   public static final char GLYPH_ASTERISK = '\ue001';
   public static final char GLYPH_ZERO = '\ue002';
   public static final char GLYPH_ONE = '\ue003';
   public static final char GLYPH_TWO = '\ue004';
   public static final char GLYPH_THREE = '\ue005';
   public static final char GLYPH_FOUR = '\ue006';
   public static final char GLYPH_FIVE = '\ue007';
   public static final char GLYPH_SIX = '\ue008';
   public static final char GLYPH_SEVEN = '\ue009';
   public static final char GLYPH_EIGHT = '\ue00a';
   public static final char GLYPH_NINE = '\ue00b';
   public static final char GLYPH_COPYRIGHT = '\ue00c';
   public static final char GLYPH_REGISTERED = '\ue00d';
   public static final char GLYPH_MAHJONG = '\ue00e';
   public static final char GLYPH_BLACK_JOKER = '\ue00f';
   public static final char GLYPH_A = '\ue010';
   public static final char GLYPH_B = '\ue011';
   public static final char GLYPH_O2 = '\ue012';
   public static final char GLYPH_PARKING = '\ue013';
   public static final char GLYPH_AB = '\ue014';
   public static final char GLYPH_CL = '\ue015';
   public static final char GLYPH_COOL = '\ue016';
   public static final char GLYPH_FREE = '\ue017';
   public static final char GLYPH_ID = '\ue018';
   public static final char GLYPH_NEW = '\ue019';
   public static final char GLYPH_NG = '\ue01a';
   public static final char GLYPH_OK = '\ue01b';
   public static final char GLYPH_SOS = '\ue01c';
   public static final char GLYPH_UP = '\ue01d';
   public static final char GLYPH_VS = '\ue01e';
   public static final char GLYPH_ASCENSION_ISLAND = '\ue01f';
   public static final char GLYPH_ANDORRA = '\ue020';
   public static final char GLYPH_UNITED_ARAB_EMIRATES = '\ue021';
   public static final char GLYPH_AFGHANISTAN = '\ue022';
   public static final char GLYPH_ANTIGUA_BARBUDA = '\ue023';
   public static final char GLYPH_ANGUILLA = '\ue024';
   public static final char GLYPH_ALBANIA = '\ue025';
   public static final char GLYPH_ARMENIA = '\ue026';
   public static final char GLYPH_ANGOLA = '\ue027';
   public static final char GLYPH_ANTARCTICA = '\ue028';
   public static final char GLYPH_ARGENTINA = '\ue029';
   public static final char GLYPH_AMERICAN_SAMOA = '\ue02a';
   public static final char GLYPH_AUSTRIA = '\ue02b';
   public static final char GLYPH_AUSTRALIA = '\ue02c';
   public static final char GLYPH_ARUBA = '\ue02d';
   public static final char GLYPH_COLOMBIA = '\ue050';
   public static final char GLYPH_CLIPPERTON_ISLAND = '\ue051';
   public static final char GLYPH_COSTA_RICA = '\ue052';
   public static final char GLYPH_CUBA = '\ue053';
   public static final char GLYPH_CAPE_VERDE = '\ue054';
   public static final char GLYPH_CURACAO = '\ue055';
   public static final char GLYPH_CHRISTMAS_ISLAND = '\ue056';
   public static final char GLYPH_CYPRUS = '\ue057';
   public static final char GLYPH_CZECH_REPUBLIC = '\ue058';
   public static final char GLYPH_DE = '\ue059';
   public static final char GLYPH_DIEGO_GARCIA = '\ue05a';
   public static final char GLYPH_DJIBOUTI = '\ue05b';
   public static final char GLYPH_UK = '\ue070';
   public static final char GLYPH_GRENADA = '\ue071';
   public static final char GLYPH_GEORGIA = '\ue072';
   public static final char GLYPH_FRENCH_GUIANA = '\ue073';
   public static final char GLYPH_GUERNSEY = '\ue074';
   public static final char GLYPH_GHANA = '\ue075';
   public static final char GLYPH_GIBRALTAR = '\ue076';
   public static final char GLYPH_GREENLAND = '\ue077';
   public static final char GLYPH_GAMBIA = '\ue078';
   public static final char GLYPH_GUINEA = '\ue079';
   public static final char GLYPH_GUADELOUPE = '\ue07a';
   public static final char GLYPH_EQUATORIAL_GUINEA = '\ue07b';
   public static final char GLYPH_GREECE = '\ue07c';
   public static final char GLYPH_SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS = '\ue07d';
   public static final char GLYPH_GUATEMALA = '\ue07e';
   public static final char GLYPH_GUAM = '\ue07f';
   public static final char GLYPH_GUINEA_BISSAU = '\ue080';
   public static final char GLYPH_GUYANA = '\ue081';
   public static final char GLYPH_HONG_KONG = '\ue082';
   public static final char GLYPH_HEARD_MCDONALD_ISLANDS = '\ue083';
   public static final char GLYPH_HONDURAS = '\ue084';
   public static final char GLYPH_CROATIA = '\ue085';
   public static final char GLYPH_HAITI = '\ue086';
   public static final char GLYPH_HUNGARY = '\ue087';
   public static final char GLYPH_CEUTA_MELILLA = '\ue060';
   public static final char GLYPH_ECUADOR = '\ue061';
   public static final char GLYPH_ESTONIA = '\ue062';
   public static final char GLYPH_EGYPT = '\ue063';
   public static final char GLYPH_WESTERN_SAHARA = '\ue064';
   public static final char GLYPH_ERITREA = '\ue065';
   public static final char GLYPH_ES = '\ue066';
   public static final char GLYPH_ETHIOPIA = '\ue067';
   public static final char GLYPH_EUROPEAN_UNION = '\ue068';

   @Generated
   private FontGlyphs() {
      throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
   }
}
